"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['The Chomsky Index.py']
DATA_FILES = ['h5', 'html', 'icon_white.png']
OPTIONS = {'includes': 'pandas._libs.tslibs.base', 'iconfile': 'icon_black.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
